# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13e868c5449055269741e1e9051d7f22b9e3549208759a89725e243e6d8253d4e9acbc178c06bc16b264ffdef5e9c48da0145234d0c7ca8f86aa2306e747ac4b

test:
  secret_key_base: 5bc4f2ed105106eb8a99e2e51152e1ad9d7e138261011d26a7fc11954fa324f0ce9438787f11fd8f1eda98da9eae644edc5da01366ec88d44a9ee432e080b838

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
